<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Telegram.Bot" Version="22.9.6.2" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.5" />
    <PackageVersion Include="MSTest" Version="4.1.0" />
    <PackageVersion Include="TqkLibrary.CompilerServices" Version="1.0.0.3" />
    <PackageVersion Include="GitVersion.MsBuild" Version="6.7.0" />
  </ItemGroup>
</Project>